file_length:
  warning: 200
  error: 201

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
disabled_rules: # rule identifiers to exclude from running
  - comma
  - vertical_whitespace
  - line_length
  - identifier_name
  - trailing_whitespace
  - colon
  - force_cast