file_length:
  warning: 200
  error: 201

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - R.generated.swift
disabled_rules: # rule identifiers to exclude from running
  - comma
  - vertical_whitespace
  - line_length
  - identifier_name
  - trailing_whitespace
  - colon
  - force_cast
  - force_try
  - void_return
  - unused_closure_parameter
  - unused_optional_binding